name: Auto Commit

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"

      - name: Make changes
        run: |
          # Modify or generate files as needed
          echo "New content" > myfile.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto-commit: Update files"
          git push
